"""empty message

Revision ID: cd74a918e06a
Revises: b09e417a82dd
Create Date: 2026-07-13 14:11:03.914132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd74a918e06a'
down_revision = 'b09e417a82dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Booked', 'Cancelled', 'Completed', name='booking_status'),
               nullable=False)

    with op.batch_alter_table('treks', schema=None) as batch_op:
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Easy', 'Moderate', 'Hard', name='difficulty_levels'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Pending', 'Approved', 'Open', 'Closed', 'Completed', name='trek_status'),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'staff', 'user', name='user_roles'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'blacklisted', name='user_status'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('active', 'blacklisted', name='user_status'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'staff', 'user', name='user_roles'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('treks', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('Pending', 'Approved', 'Open', 'Closed', 'Completed', name='trek_status'),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.Enum('Easy', 'Moderate', 'Hard', name='difficulty_levels'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('booking_status',
               existing_type=sa.Enum('Booked', 'Cancelled', 'Completed', name='booking_status'),
               type_=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
